# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-26 01:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invitations', '0003_auto_20151126_1523'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitation',
            name='message',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
