# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-26 01:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invitations', '0004_invitation_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitation',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
